In [11]:
import numpy as np
import pandas as pd

In [12]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10])
counts = np.bincount(a)
print(np.argmax(counts))

10


In [13]:
from collections import Counter 

def most_frequent(List): 
    occurence_count = Counter(List) 
    return occurence_count.most_common(1)[0][0] 
    
List = ['a','b','a'] 
print(most_frequent(List)) 

a


In [46]:
df = pd.DataFrame()
df['prova']=[1,4,4,4,8]
df['test']=[100,300,300,300,100]
df['target']=[1,3,3,3,10]

In [44]:
df

prova  test  target
0      1     1       1
1      2     3       3
2      2     3       3
3      4     3       3
4      5    10      10

In [27]:
def create_level_variable_matrix(dataframe,feature, local=None):
    
    x_j_k = np.unique(dataframe[feature].to_list())
    if local is None:
        x_most_freq = dataframe.apply(lambda x: most_frequent(x),axis=0)
    else:
        x_most_freq = dataframe.loc[local]
    
    Z = pd.DataFrame( x_most_freq ).T
    Z = pd.concat([Z]*len(x_j_k), ignore_index=True)
    Z[feature] = x_j_k
    Z['quantile'] = np.linspace(0,1,len(x_j_k))
    
    return Z

In [45]:
create_level_variable_matrix(df,'prova',local=0)

prova  test  target  quantile
0      1     1       1  0.000000
1      2     1       1  0.333333
2      4     1       1  0.666667
3      5     1       1  1.000000

In [30]:
def create_quantile_feature_matrix(dataframe, feature, target, K, local = None):
    '''
    Create a matrix with K row, made by all the columns dataframe mean values, except for the "feature", which is replaced by K quantiles of the feature empiracal distribution
    '''
    if K > 2:
        quantile = np.linspace(0,1,K)
    if K == 2:
        quantile = [ 0.01, 0.99 ]
    x_j = dataframe[feature].values
    x_j_k = np.quantile(x_j,quantile)
    if local is None:
        x_mean = dataframe.drop(columns = [target]).mean()
    else:
        x_mean = dataframe.drop(columns = [target]).loc[local]
    Z = pd.DataFrame( x_mean ).T
    Z = pd.concat([Z]*len(x_j_k), ignore_index=True)
    Z[feature] = x_j_k
    Z['quantile'] = quantile
    
    return Z

In [33]:
a=create_quantile_feature_matrix(df,'prova','target',K=10)

In [39]:
b = a.apply(lambda x: most_frequent(x),axis=0)

In [42]:
pd.DataFrame(b).T

prova  test  quantile
0    2.0   4.0       0.0

In [48]:
from statwolfml import Builder
model= 'random_forest_regressor'
build_model = Builder(model).feature_names([]).labels(['target']).build()
train_model = build_model.train(df)

In [54]:
print(train_model.base_model()['model'].predict(df[['test','prova']]))
print(train_model.base_model()['model'].predict(df[['prova','test']]))

[7.81 7.81 7.81 7.81 7.81]
[2.62 2.98 2.98 2.98 7.81]


In [56]:
train_model.base_model()['model'].predict(df.drop(columns='target'))

array([2.62, 2.98, 2.98, 2.98, 7.81])

In [61]:
def clean_list(List,to_keep):
    out = List.copy()
    for i in List:
        if i not in to_keep:
            out.remove(i)
    return out

In [63]:
clean_list(['a','b','c','d','e'],['b','a','e'])

['a', 'b', 'e']

In [64]:
from data_science.modules.load_dataset import create as createLD

In [70]:
createLD().classification_bin().dataframe()

target  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   
5         0       3                                    Mr. James Moran   
6         0       1                             Mr. Timothy J McCarthy   
7         0       3                      Master. Gosta Leonard Palsson   
8         1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson   
9         1       2                 Mrs. Nicholas (Adele Achem) Nasser   
10        1       3                     Miss. Marguerite Rut Sandstrom   
11        1       1                            Miss. Elizabeth Bonnell   
12        0       3                      Mr. William Henry Saundercock   
13        0       3                         Mr. Anders Johan Andersson   
14        0       3                Miss. Hulda Amanda Adolfina Vestrom   
15        1       2                     Mrs. (Mary D Kingcome) Hewlett   
16        0       3                                Master. Eugene Rice   
17        1       2                        Mr. Charles Eugene Williams   
18        0       3  Mrs. Julius (Emelia Maria Vandemoortele) Vande...   
19        1       3                             Mrs. Fatima Masselmani   
20        0       2                                Mr. Joseph J Fynney   
21        1       2                               Mr. Lawrence Beesley   
22        1       3                                 Miss. Anna McGowan   
23        1       1                        Mr. William Thompson Sloper   
24        0       3                       Miss. Torborg Danira Palsson   
25        1       3  Mrs. Carl Oscar (Selma Augusta Emilia Johansso...   
26        0       3                             Mr. Farred Chehab Emir   
27        0       1                      Mr. Charles Alexander Fortune   
28        1       3                                Miss. Ellen O'Dwyer   
29        0       3                                 Mr. Lalio Todoroff   
..      ...     ...                                                ...   
857       0       2                         Mr. Frederick Edward Giles   
858       1       1  Mrs. Frederick Joel (Margaret Welles Barron) S...   
859       0       3                           Miss. Dorothy Edith Sage   
860       0       2                              Mr. John William Gill   
861       1       2                            Mrs. (Karolina) Bystrom   
862       1       2                        Miss. Asuncion Duran y More   
863       0       1                Mr. Washington Augustus II Roebling   
864       0       3                         Mr. Philemon van Melkebeke   
865       1       3                     Master. Harold Theodor Johnson   
866       0       3                                   Mr. Cerin Balkic   
867       1       1    Mrs. Richard Leonard (Sallie Monypeny) Beckwith   
868       0       1                            Mr. Frans Olof Carlsson   
869       0       3                         Mr. Victor Vander Cruyssen   
870       1       2               Mrs. Samuel (Hannah Wizosky) Abelson   
871       1       3                           Miss. Adele Kiamie Najib   
872       0       3                       Mr. Alfred Ossian Gustafsson   
873       0       3                                Mr. Nedelio Petroff   
874       0       3                                  Mr. Kristo Laleff   
875       1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter   
876       1       2        Mrs. William (Imanita Parrish Hall) Shelley   
877       0       3                                  Mr. Johann Markun   
878       0       3                        Miss. Gerda Ulrika Dahlberg   
879      